Python podstawowy:
  Opis:
    Szkolenie obejmuje naukę podstaw programowania dla osób zupełnie początkujących jak również wszystkie najważniejsze zagadnienia potrzebne na start dla Python developera.
  Lekcje:
    Wprowadzenie:
      - Informacje o języku
      - Instalacja środowiska
      - PyCharm - utworzenie projektu
      - PyCharm - elementy IDE
      - Jupyter Notebook
    Podstawy:
      - Definiowanie zmiennych
      - Komentarze
      - Typy
      - Funkcje wbudowane
      - Operacje arytmetyczne
      - Operacje na stringach
      - Funkcja input
    Struktury danych:
      - list
      - tuple
      - dict
      - set
      - Operacje na strukturach danych
      - Slicing
      - Zagnieżdżone struktury
      - Wbudowane generatory cz. 1
      - Mutowalność, hashowalność i kopiowanie obiektów
    Instrukcje warunkowe:
      - Operatory porównania
      - Spójniki logiczne
      - Instrukcja if
      - Instrukcja if-else
      - Instrukcja if-elif-(else)
    Pętle:
      - Pętla for
      - Pętla while
      - Instrukcje break oraz continue
      - Zagnieżdżone pętle
      - zip i enumerate w pętli for
      - list comprehension
    Funkcje:
      - Procedura
      - Parametry funkcji
      - Słowo kluczowe return
      - Parametry z wartością domyślną
      - Wbudowane generatory cz. 2
      - lambda
      - arguments unpacking
      - args, kwargs
      - Kolejność parametrów
      - Docstring i doctest
      - Zakres przestrzeni nazw
    Jakość kodu i obsługa błędów:
      - PEP 8
      - Type annotations
      - Stack Overflow
      - Debugowanie
      - Linebreak
      - Wyjątki
    Moduły:
      - Ogólne informacje
      - Przykładowe moduły biblioteki standardowej
      - Import kodu z innych plików
    Programowanie obiektowe:
      - Klasa oraz obiekt
      - Definicja klasy, konstruktor, atrybuty
      - Metody
      - staticmethod, classmethod
      - Dziedziczenie
      - Stringifikacja i reprezentacja
      - class attribute
    Praca z plikami:
      - Pliki txt
      - Kodowanie znaków
      - Pliki json
      - pickle
      - Biblioteka os
Python średniozaawansowany:
  Opis:
    To szkolenie skupia się na pogłębieniu wiedzy i rozwijaniu umiejętności programowania w Pythonie. Obejmuje m.in. zagadnienia związane z wyrażeniami regularnymi, wykorzystaniem protokołu HTTP czy łączeniem się z bazą danych.
  Lekcje:
    Data i czas:
     - Typy date, time i datetime
     - Części składowe daty i czasu
     - Zamiana daty na tekst i tekstu na datę
     - Strefy czasowe
     - Obsługa kalendarza
    Wyrażenia regularne:
     - Wprowadzenie
     - Proste patterny
     - Znaki specjalne
     - Escape character
     - Złożone patterny
     - Funkcje biblioteki re
    Bazy danych:
     - Wstęp do baz danych i podstawy SQL
     - Nawiązanie połączenia
     - Generowanie i egzekucja zapytań SQL w Pythonie
    Protokół HTTP:
     - Podstawowe pojęcia
     - Web scraping
     - REST API
    Aplikacje CLI:
     - Parsowanie argumentów skryptu
     - Tworzenie aplikacji CLI
    Logowanie:
     - Idea logowania
     - Konfiguracja loggera
     - Strumienie wyjścia
    Testy jednostkowe:
     - Asercje
     - Biblioteka pytest
     - Fixtures
     - Test Driven Development
    Pozostałe zagadnienia:
     - Klasa Enum
     - dataclass
     - Pliki konfiguracyjne
     - Statyczna analiza kodu
     - Generatory oraz iteratory
     - Dekoratory
Analiza danych|todo:
  Opis:
    To szkolenie wprowadza w świat analizy danych i daje fundament do dalszego rozwoju w kierunku data science i uczenia maszynowego
  Lekcje:
    Wprowadzenie:
      - Informacje ogólne
      - Jupyter Notebook
    Numpy - tablice:
      - Wektory i macierze
      - Zapis i odczyt tablic z pliku
      - Kształt oraz wymiar tablicy
      - Typy danych w tablicach
      - Rozmiar tablicy
      - Slicing
      - Slicing z użyciem warunków logicznych
      - Zmiana kształtu tablicy
      - Sortowanie
    Numpy - operacje matematyczne:
      - Podstawowe operacje matematyczne
      - Operacje logiczne
      - Algebra liniowa
      - Funkcje agregujące
    Numpy - pozostałe zagadnienia:
      - Broadcasting
      - Kopiowanie tablic
      - Obroty tablic i wyciąganie przekątnej
      - Łączenie tablic
      - Liczby pseudolosowe
    Pandas - series i dataframe:
      - Series
      - DataFrame
    Pandas - operacje odczytu:
      - Struktura dataframe'a
      - Wyciąganie kolumn, wierszy, wartości
      - Wartości unikalne
      - Filtrowanie dataframe'a
      - Wykresy
    Pandas - operacje zapisu:
      - Modyfikacja istniejących wartości
      - Sortowanie
      - Tworzenie nowych kolumn
      - Operacje na kolumnach
      - Dodawanie wierszy
    Pandas - pozostałe operacje:
      - Grupowanie i agregacja
      - Łączenie tabel
      - Wczytywanie dużych zbiorów danych
      - Indeks hierarchiczny
      - Data i czas
      - Wybrane pozostałe funkcje
    Matplotlib - typy wykresów:
      - Wykres punktowy
      - Wykres liniowy
      - Wykres słupkowy
      - Histogram
      - Heatmapa
    Matplotlib - stylowanie wykresów:
      - Kolory i kształty
      - Opisy osi oraz tytuł wykresu
      - Ticki
      - Legenda i siatka
      - Podwykresy
      - Zapis do pliku
      - Colorbar
    Matplotlib - zaawansowane stylowanie wykresów:
      - Stylowanie ticków
      - Dwie osie pionowe
      - Współdzielenie osi
    Seaborn:
      - Boxplot
